import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import RefreshTokenProvider from "@/components/wrap/RefreshToken";
import SetTheme from "@/components/wrap/SetTheme";
import SessionProviders from "@/components/wrap/SessionProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "QuickChat",
  description: "Generated by create next app",
  icons: {
    icon: "../../public",
    shortcut: "message-icon.png",
    apple: "message-icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SessionProviders>
          <RefreshTokenProvider>
            <SetTheme>{children}</SetTheme>
          </RefreshTokenProvider>
          <Toaster richColors position="top-right" />
        </SessionProviders>
      </body>
    </html>
  );
}
